services:
  database:
    image: bitnami/postgresql:17
    container_name: babershop_db
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=babershop
    ports:
      - 5432:5432