services:
  database:
    image: bitnami/postgresql:17
    container_name: barbershop_db
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=barbershop
    ports:
      - 5432:5432